routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// frontend
// -------------------------------------------- front end -------------------------------------------------
Route::get('item/category/{slug}', ['as' => 'item.getproducts', 'uses' => 'Frontend\ProductController@showproducts']);
// Route::get('/item/fetch','Frontend\ProductController@fetch'); //fetchforsorting
// Route::post('item/index1',['as' => 'item.index1', 'uses' => 'Frontend\ProductController@index']);
Route::get('/','Frontend\ProductController@index');
Route::get('/about','Frontend\PageController@getAbout');

Route::get('/contact-us','Frontend\PageController@getContact');
Route::post('/contact-us','Frontend\PageController@postContact');

// store all product listing 
Route::get('/store',['as' => 'item.sort', 'uses' => 'Frontend\ProductController@getstore']);

// Route::get('/getCategoryProduct/{id}',['as'=>'item.getCategoryProduct','uses' =>'Frontend\ProductController@getCategoryProduct']);
// Route::get('/getSubCategoryProduct/{id}',['as'=>'item.getSubCategoryProduct','uses' =>'Frontend\ProductController@getSubCategoryProduct']);
Route::resource('/item','Frontend\ProductController');

//search for products in frontend
Route::get('/searchitem',['as' =>'item.getsearch', 'uses' => 'Frontend\ProductController@getSearch']);

//for product enquiry form
Route::resource('enquire','EnquiryController');
// enquiry mail
// Route::get('/enquire/{slug}','Frontend\ProductController@getEnquire');
// Route::post('/enquire','Frontend\ProductController@postEnquire');

// frone end ends------------------------------------------------------------------------

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => ['auth']], function(){
	// products
	Route::post('product/fetch','ProductController@fetch');
	Route::post('product/fetchsub','ProductController@fetchsub');
	Route::post('product/fetchsubcat1','ProductController@fetchsubcat1');
	Route::delete('product/delete/{slug}', ['as' => 'product.destroysearch', 'uses' => 'ProductController@destroysearch']);
	Route::resource('product','ProductController');

	Route::get('/search','ProductController@getSearch');
	

	// Route::get('/getcategoryproduct/{category_id}','ProductController@getCategoryProduct');
	// Route::get('/getsubcategoryproduct/{subcategory_id}','ProductController@getSubCategoryProduct');
	// Route::get('/getsubcategory1product/{subcategory_id}','ProductController@getSubCategory1Product');

	// categories
	Route::get('category/{category_id}/subcategory','CategoryController@editSubCategory');
	Route::resource('category','CategoryController',['except' => ['create'],['destroy']]);

	// update subcategory
	Route::post('subcategory/', ['as' => 'subcategory.update', 'uses' => 'CategoryController@updatesubcategory']);
	// dashboard
	Route::get('/dashboard', 'PageController@getDashboard');
	// getting about page
	Route::get('/getabout', ['as' => 'page.getabout', 'uses' => 'PageController@getAbout']);
	Route::post('postabout', ['as' => 'page.about', 'uses' => 'PageController@postAbout']);
	// getting contact page
	// Route::get('/getcontact', 'PageController@getContact');
	// Route::post('postcontact', ['as' => 'page.contact', 'uses' => 'PageController@postcontact']);

	//user registration
	Route::group(['middleware' => ['user']],function(){
		Route::resource('users','UserController');
	});
	Route::get('/profile/{user_id}','UserController@getProfile');
	Route::post('/profile/edit',['as' => 'profile.edit', 'uses' => 'UserController@updateInformation']);
	Route::get('enquiries/{slug}',['as' => 'enquire.list','uses' => 'EnquiryController@showenquiries']);
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function product(){
    	return $this->belongsToMany('App\Product');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use app\Product;
use Illuminate\Http\Request;
use Image;
use Illuminate\Support\Facades\File;
use Session;

class CategoryController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all()->sortBy('name');
        return view('categories.index')->withcategories($categories);
    }

    public function editSubCategory($id){
        $subCategory = Category::find($id);
        // return redirect()->back()->with('subcategory',$subCategory);
        return view('categories.editsubCategory')->with('subcategory',$subCategory);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
                'image' => 'image|max:4096',
                'name'=>'required|max:255'));

        $category = new Category();

        $category->name = $request->name; 
        $category->slug = str_slug($request->name);
        
        if($request->subcategory1_id !=null)
        {
            $category->pid = $request->subcategory1_id;
        }
        elseif($request->category_id == null && $request->subcategory_id != null)
        {
            $category->pid = $request->subcategory_id;           
        }
        elseif($request->category_id == null){
            $category->pid = 0;
        }
        elseif($request->category_id != null && $request->subcategory_id != null)
        {
            $category->pid = $request->subcategory_id;
        }
        else{
            $category->pid = $request->category_id;
        }

        // saving the image of category
        if($request->hasFile('image')){
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension(); //encode('png')
            $image = Image::make($image)->save(public_path('images/category/' . $filename));
            // $image->fit(110,100)->save(public_path('images/' . $filename . '-thumbs.png'));

            $category->image = $filename;   
        }

        $category->status = 1;
        $category->save();

        Session::flash('success','New Category Created Successfully');

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        return view('categories.show')->with('category',$category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategories = Category::all()->sortBy('name');
        $category = Category::find($id);
        return view('categories.edit')->with('category',$category)->with('subcategories',$subcategories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $this->validate($request, array(
                'image' => 'image|max:4096',
                'name'=>'required|max:255'));

        $category->name = $request->input('name');
        $category->slug = str_slug($request->name);

        if($request->hasFile('image'))
        {
            // add the new photo
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension(); 
            $image = Image::make($image)->save(public_path('images/category/' . $filename));
            // $image->fit(110,100)->save(public_path('images/' . $filename . '-thumbs.png'));        
            $oldfilename = $category->image;
            // $oldfilenamethumb = $category->image . '-thumbs.png';
            // update the database 
            $category->image = $filename;   
            // delete the old photo
            $path = public_path()."\images\category".'\\';
            // dd($path);
            File::delete($path.$oldfilename);
        }

        $category->save();

        Session::flash('success','Category Updated Successfully !!');

        return redirect()->back();  
    }
    public function updatesubcategory(Request $request)
    {
        $id = $request->subcat_id;
        $name = $request->name;
        
        $category = Category::find($id);
        $this->validate($request, array(
                'name'=>'required|max:255'));

        $category->name = $name;
        $category->slug = str_slug($name. '-' .rand(0,200));
        $category->save();

        Session::flash('success','Category Updated Successfully !!');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subcategories = Category::where('pid', '=', $id);
        $subcategories->delete();
        
        $category = Category::find($id);
        $category->product()->detach();
        $path = public_path()."\images\category".'\\';
        // dd($path);
        File::delete($path.$category->image);
        // File::delete($path.$category->image);
        $category->delete();

        Session::flash('success','Category Deleted Successfully !!');
        return redirect()->route('category.index');
    }
}

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('title','| Categories')
@section('pageheader','Categories')
@section('pageminiheader','Category Lists')
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('category.index')}}"><i class="fa fa-bullseye"></i> Category</a></li>
    <li class="active">Category Lists</li>
  </ol>
@endsection
@section('content')
<style type="text/css">
	.subcategorys{list-style: none;}
	.subcategorys li{margin-bottom: 5px;}
</style>

<style>
	.subCategories{
		margin-left: 20px;
	}
    
    .deletebtn{
    	padding: 3px 3px;
    	height: 20px;
    	margin-right: 6px;
        color: ;
        background: #fff;
        border: none;
        border-radius: 2px;
        margin-top: -18	px;
    }
    .subcategorys ul li{margin-bottom: 10px; border-bottom: 1px solid #ccc; padding: 20px}
</style>


<div class="row">
	<div class="col-sm-12 col-md-8 col-lg-8" style="margin-top: 5px;">
		<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
		    <thead>
		        <tr>
		            <th class="th-sm">#
		            </th>
		            <th class="th-sm">Name
		            </th>
		            <th class="th-sm">Actions
		            </th>
		        </tr>
		    </thead>
		    <tbody>
		    	@php
            		$count = 1;
       			@endphp
		        @foreach($categories as $category)
			       	@if($category->pid == 0)
				        <tr>
				            <td>@php echo $count++ @endphp</td>
				            <td>
					           	<h4>
					           		<a href="{{ route('category.show', $category->id) }}">{{ $category->name}}</a> 
					           		<!-- <i class="fas fa-caret-down pull-right" onclick="hideitem('{{$category->id}}');" style="cursor: pointer;"></i> -->
					           	</h4>
					           	<ul class="subcategorys" id="subcat_{{$category->id}}">
					           	@foreach($categories as $cat)
					           		@if($cat->pid == $category->id)
										
											<li>
												<a href="{{ route('category.show', $cat->id) }}"> 
													<i class="fas fa-caret-right" style="color: #3c8dbc;"></i> {{ $cat->name }}
												</a>
												
												<a href="{{ route('category.edit', $cat->id)}}" class="">
													<i class="fas fa-pen pull-right" title="edit"></i> 
												</a>

												
												<!-- delete button -->
				              		 			{{ Form::open(['route' => ['category.destroy', $cat->id], 'method' => 'DELETE', 'id' => 'deleteform', 'style' => 'margin-left: 453px; margin-top: -23px;' , 'onclick' => 'deletecategory(event)']) }} 
                        							<button type="submit" id="deletebtn" class="deletebtn "><i class="fas fa-trash-alt" title="delete"></i></button>
				                				{!! Form::close() !!}
				                				<!-- delete -->
				               			    </li>

												<!-- sub sub categories -->
												@foreach($categories as $subcat1)
												@if($subcat1->pid == $cat->id)
												<ul style="list-style: none;">
													<li class="row">
														<a href="{{ route('category.show', $subcat1->id) }}"> <i class="fas fa-caret-right" style="color: #3c8dbc;"></i> {{ $subcat1->name}}
														</a>
														<a href="{{ route('category.edit', $subcat1->id)}}" class="">
															<i class="fas fa-pen pull-right" title="edit"></i> 
														</a>	
														
							              		 		{{ Form::open(['route' => ['category.destroy', $subcat1->id], 'method' => 'DELETE', 'id' => 'deleteform', 'style' => 'margin-left: 453px; margin-top: -23px;' ,  'onclick' => 'deletecategory(event)']) }} 
			                        						<button type="submit" id="deletebtn" class="deletebtn pull-right"><i class="fas fa-trash-alt" title="delete"></i></button>
							                			{!! Form::close() !!}
							                			
							                			<ul style="list-style: none;">
														@foreach($categories as $subcat2)
														@if($subcat2->pid == $subcat1->id)
														
															<li>
																<a href="{{ route('category.show', $subcat2->id) }}"> <i class="fas fa-caret-right" style="color: #3c8dbc;"></i> {{ $subcat2->name}}</a>

																<a href="{{ route('category.edit', $subcat1->id)}}" class=""><i class="fas fa-pen pull-right" title="edit"></i> </a>	
																
									              		 		{{ Form::open(['route' => ['category.destroy', $subcat1->id], 'method' => 'DELETE', 'id' => 'deleteform',  'style' => 'margin-left: 439px; margin-top: -23px;' ,   'onclick' => 'deletecategory(event)']) }} 
					                        						<button type="submit" id="deletebtn" class="deletebtn pull-right"><i class="fas fa-trash-alt" title="delete"></i></button>
									                			{!! Form::close() !!}
									                			
															</li>
														
														@endif
							               			   	@endforeach
							               			   	</ul>

													</li>
												</ul>
												@endif
					               			   	@endforeach
										@endif
								@endforeach
								</ul>
				            </td>
				            
				            <td>
				            	<!-- delete button -->
				                {{ Form::open(['route' => ['category.destroy', $category->id], 'method' => 'DELETE', 'id' => 'deleteform',  'onclick' => 'deletecategory(event)']) }} 
		    						<button type="submit" id="deletebtn" class="deletebtn pull-left" style="margin-top: 1px; color: red;"><i class="fas fa-trash-alt" title="delete"></i></button>
							    {!! Form::close() !!}
				                <!-- delete button -->
				          
				                <a href="{{ route('category.edit', $category->id)}}" class="btn-md"><i class="fas fa-pen" title="edit" style="margin-top: 5px; margin-left: 5px;"></i> </a>
				          		<!-- <a href="{{ route('category.show', $category->id)}}" class="btn btn-primary btn-success btn-xs">View</a>       -->
				            </td>
				        </tr>
			        @endif
		        @endforeach
		    </tbody>
		    <!-- <tfoot>
		         <tr>
		            <th class="th-sm">#
		            </th>
		            <th class="th-sm">Name
		            </th>
		            <th class="th-sm">Actions
		            </th>
		        </tr>
		    </tfoot> -->
		</table>
	</div>
	
	<div class="col-md-4 col-sm-12" style="margin-top: 5px;">
		{!! Form::open(['route' => 'category.store', 'method' => 'POST', 'files' => 'true']) !!}
		<div class="box box-primary">
			<div class="box-header with-border">
        		<h3 class="box-title">New Category</h3>
      		</div>
      		<div class="box-body">
      			<div class="form-group">
						<input type="text" name="name" class="form-control" placeholder="name">
				</div>
				<div class="form-group">
		          {{Form::label('image','Image') }}
		          {{ Form::file('image', ['class'=>'form-control']) }}
		        </div>
      		</div>
		</div>

		<div class="box box-primary">
			<div class="box-header with-border">
				<div class="box-title">
					Select Parent
				</div>
			</div>
			<div class="box-body">
				<div class="form-group">
					@foreach($categories as $category)
					@if($category->pid == 0)
					<div class="radio">
						<label for="">
							<input type="radio" value="{{ $category->id}}" name="category_id"> <p style="font-size: 16px; margin: 0px;">{{ $category->name }}</p>
						</label>
					</div>
						@foreach($categories as $cat)
						@if($cat->pid == $category->id)
						<ul style="list-style: none;">
							<li>
								<div class="radio">
									<label for="">
										<input type="radio" value="{{ $cat->id}}"  name="subcategory_id" > <p style="font-size: 14px; margin: 0px;">{{ $cat->name}}</p>
									</label>
								</div>
							</li>
						
							<ul style="list-style: none;">
								<li>
									@foreach($categories as $sub1cat)	
									@if($sub1cat->pid == $cat->id)
									<div class="radio">
										<label for="">
											<input type="radio" value="{{ $sub1cat->id}}"  name="subcategory1_id" > <p style="font-size: 14px; margin: 0px;">{{ $sub1cat->name}}</p>
										</label>
									</div>
									<ul style="list-style: none;">
										<li>
											@foreach($categories as $sub2cat)
											@if($sub2cat->pid == $sub1cat->id)
												<div class="radio">	
													<label for="">
														<i class="fas fa-caret-right"></i> {{$sub2cat->name}}  
														<!-- <a href="{{ route('category.edit', $sub2cat->id)}}"> 
															<i class="fas fa-pen" style="margin-left: 55px; color : black;"></i>	 
														</a>
														<i class="fas fa-trash-alt" style="margin-left: 10px;"></i>
														<hr style="margin-top: 3px; margin-bottom: 0px;"> -->
													</label>
												</div>
											@endif
											@endforeach
										</li>
									</ul>
									@endif
									@endforeach
								</li>
							</ul>
						</ul>
						@endif
						@endforeach
						<hr style="margin-top: 3px; margin-bottom: 0px;">							
					@endif
					@endforeach

					{{ Form::submit('Create',['class' => 'btn btn-success btn-block btn-sm'])}}
				</div>
			</div>
		</div>
		{!! Form::close() !!}	
	</div>	
</div>
	
@endsection
@section('javascripts')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        // function hideitem(id){
       	// 	$('#subcat_'+id).toggle("slide");
        // }

    </script>
	<script>
    function deletecategory(e){
            if(confirm('Are you Sure you want to delete ?')){
                $(this).submit();
            }
            else{
                e.preventDefault();
            }
        }
    </script>
	<!-- <script>
	    $(document).ready(function(){
	        $('#deletebtn').click(function(e){
	            if(confirm('Are you Sure you want to delete ?')){
	                $('#deleteform').submit();
	            }
	            else{
	                e.preventDefault();
	            }
	        e.preventDefault();
	        });
	    });
    </script> -->

<!--data table ends  -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
@endsection

resources/views/categories/searchresult.blade.php
@extends('layouts.app')
@section('title','| Search result')
@section('pageheader','Categories')
@section('pageminiheader','Search Results')
@section('content')
<style type="text/css">
	.subcategorys{list-style: none;}
	.subcategorys li{margin-bottom: 5px;}
</style>
<div class="row">
	<div class="col-sm-8 col-md-8 col-lg-8">
		<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
		    <thead>
		        <tr>
		            <th class="th-sm">#
		            </th>
		            <th class="th-sm">Name
		            </th>
		            <th class="th-sm">Actions
		            </th>
		        </tr>
		    </thead>
		    <tbody>
		    	@php
            		$count = 1;
       			@endphp
		        @foreach($categories as $category)
			       	@if($category->pid == 0)
				        <tr>
				            <td>@php echo $count++ @endphp</td>
				            <td>
					           	<h4><a href="/getcategoryproduct/{{$category->id}}">{{ $category->name}}</a> 
					           		<i class="fas fa-caret-down pull-left" onclick="hideitem('{{$category->id}}');" style="cursor: pointer;"></i></h4>
					           	<ul style="display: none;" class="subcategorys" id="subcat_{{$category->id}}">
					           	@foreach($subcategories as $cat)
					           		@if($cat->pid == $category->id)
										
											<li><a href="/getsubcategoryproduct/{{ $cat->id}}"> {{ $cat->name}}</a>
											<!-- <a href="category/{{ $cat->id}}/subcategory" class="btn btn-xs pull-left" style="margin-top: -18px;">Edit</a> -->
											<!-- delete button -->
				              		 		{{ Form::open(['route' => ['category.destroy', $cat->id], 'method' => 'DELETE', 'id' => 'deleteform']) }} 
				                    			{!!  Form::submit('Delete',['class' =>'btn btn-none btn-xs pull-right', 'id' => 'deletebtn', 'style' => 'margin-top:-18px;']) !!} 
				                			{!! Form::close() !!}
				               				 <!-- delete button -->
				               				 </li>
										
										@endif
								@endforeach
								</ul>
				            </td>
				            
				            <td>
				            	<!-- delete button -->
				               <!--  {{ Form::open(['route' => ['category.destroy', $category->id], 'method' => 'DELETE'	]) }} 
				                    {!!  Form::submit('Delete',['class' =>'btn btn-danger btn-xs pull-left', 'id' => 'deletebtn']) !!} 
				                {!! Form::close() !!} -->
				                <!-- delete button -->
				          
				                <a href="{{ route('category.edit', $category->id)}}" class="btn btn-primary btn-xs">Edit</a>
				          		<!-- <a href="{{ route('category.show', $category->id)}}" class="btn btn-primary btn-success btn-xs">View</a>       -->
				            </td>
				        </tr>
			        @endif
		        @endforeach
		    </tbody>
		    <tfoot>
		         <tr>
		            <th class="th-sm">#
		            </th>
		            <th class="th-sm">Name
		            </th>
		            <th class="th-sm">Actions
		            </th>
		        </tr>
		    </tfoot>
		</table>
	</div>

	<div class="col-sm-4 col-md-4 col-lg-4">
		<div class="jumbotron" style="padding: 18px; border: 1px solid silver;background-color:white;">
			<p class="display-4">New Category</p>
			{!! Form::open(['route' => 'category.store', 'method' => 'POST']) !!}
			<div class="lead">
				{{ Form::text('name',null, ['class' => 'form-control'])}}
			</div>
			@if(!$categories->isEmpty() )
				<div class="lead">
					<ul style="list-style: none; font-size: 18px;">
						@foreach($categories as $category)
							@if($category->pid == 0)
									<li><input type="radio" value="{{ $category->id}}" name="category_id">{{ $category->name }}
										@foreach($subcategories as $cat)
												@if($cat->pid == $category->id)
													<ul  style="list-style: none;">
														<li>-{{ $cat->name}}</li>
													</ul>
												@endif
										@endforeach
									</li>
							@endif
						@endforeach
					</ul>
				</div>
			@endif
			
			<div class="lead">
				{{ Form::submit('Create',['class' => 'btn btn-success btn-block'])}}
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>
<style>
	.subCategories{
		margin-left: 20px;
	}
</style>	
@endsection
@section('javascripts')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });

        function hideitem(id){
       		$('#subcat_'+id).toggle("slide");
        }

    </script>

	<script>
	    $(document).ready(function(){
	        $('#deletebtn').click(function(e){
	            if(confirm('Are you Sure you want to delete ?')){
	                $('#deleteform').submit();
	            }
	            else{
	                e.preventDefault();
	            }
	        e.preventDefault();
	        });
	    });
    </script>

<!--data table ends  -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')
@section('title',"| $category->name") 
@section('pageheader','Products') 
@section('pageminiheader', "found in $category->name category" )
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('product.index')}}"><i class="fas fa-box-open"></i> Product</a></li>
    <li class="active">View Products</li>
  </ol>
@endsection 
@section('content')
<div class="col-md-12">
    <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="th-sm">#
                </th>
                <th class="th-sm">Name
                </th>
                <th class="th-sm">Rate
                </th>
                <th class="th-sm">Quantity
                </th>
                <th class="th-sm">Category
                </th>
                <th class="th-sm">Description
                </th>
                <th class="th-sm">Image
                </th>
                <th class="th-sm">Purchase Date
                </th>
                <th class="th-sm">Actions
                </th>
            </tr>
        </thead>
        <tbody>

            @php
                $count = 1;
            @endphp
            @foreach($category->product as $product)
            <tr>
                <td>@php echo $count++ @endphp</td>
                <td>{{ $product['name']}}</td>
                <td>{{ $product['rate']}}</td>
                <td>{{ $product['quantity']}}</td>
                <td>
                    @foreach($product->category as $cats)
                    <a href="{{ route('category.show', $cats->id) }}">
                        <span class="badge badge-primary" style="background-color: #6196ed; height: 20px; margin-top: 5px;"> {{ $cats->name }} </span>
                    </a>
                    <br>
                    @endforeach
                </td>
                <td>{!! substr($product['description'],0,20) !!}{{ (strlen($product['description']))>10 ? '....' : '' }}</td>
                <td style="text-align: center;">
                    <a href="{{ asset('images/' .$product['image'] ) }}">
                        <img src="{{ asset('images/' . $product['image'] .'-thumbs.png') }}" alt="" class="">    
                    </a>            
                </td>
                <td>{{ date('M j, Y h:ia',strtotime( $product['created_at'])) }}</td>
                <td>                    
                    <a href="{{ route('product.show', $product['slug'])}}"><i class="fas fa-eye pull-left" style="margin-right: 10px;" title="view" ></i></a>
                    <a href="{{ route('product.edit', $product['id'])}}"> <i class="fas fa-pen pull-left" style="margin-right: 10px;" title="edit"></i></a>
                    <!-- delete button -->
                    {{ Form::open(['route' => ['product.destroy', $product['id']], 'method' => 'DELETE', 'id' => 'deleteform', 'class' =>'pull-left','onclick' => 'deleteproduct(event)']) }} 
                        <!-- {!!  Form::submit('Delete',['class' =>'btn btn-xs delelteprod','style' =>'margin-top : 0px', 'id' => 'deletebtn']) !!}  -->
                        <button type="submit" id="deletebtn" class="deleteprod"><i class="fas fa-trash-alt pull-left" title="delete" ></i></button>
                    {!! Form::close() !!}
                    <!-- delete button -->

                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>#</th>
                <th>Name
                </th>
                <th>Rate
                </th>
                <th>Quantity
                </th>
                <th>Category
                </th>
                <th>Description
                </th>
                <th>Image
                </th>
                <th>Purchase Date
                </th>
                <th>Actions
                </th>
            </tr>
        </tfoot>
    </table>

    <style>
          .deleteprod{
            color: red;
            background: none;
            border: none;
          }      
    </style>

</div>
@endsection
@section('javascripts')
    
    
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');     
        });
    </script>

    <script>
    function deleteproduct(e){
            if(confirm('Are you Sure you want to delete ?')){
                $(this).submit();
            }
            else{
                e.preventDefault();
            }
        }
    </script>

<!--data table ends  -->
@endsection