routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// frontend
// -------------------------------------------- front end -------------------------------------------------
Route::get('item/category/{slug}', ['as' => 'item.getproducts', 'uses' => 'Frontend\ProductController@showproducts']);
// Route::get('/item/fetch','Frontend\ProductController@fetch'); //fetchforsorting
// Route::post('item/index1',['as' => 'item.index1', 'uses' => 'Frontend\ProductController@index']);
Route::get('/','Frontend\ProductController@index');
Route::get('/about','Frontend\PageController@getAbout');

Route::get('/contact-us','Frontend\PageController@getContact');
Route::post('/contact-us','Frontend\PageController@postContact');

// store all product listing 
Route::get('/store',['as' => 'item.sort', 'uses' => 'Frontend\ProductController@getstore']);

// Route::get('/getCategoryProduct/{id}',['as'=>'item.getCategoryProduct','uses' =>'Frontend\ProductController@getCategoryProduct']);
// Route::get('/getSubCategoryProduct/{id}',['as'=>'item.getSubCategoryProduct','uses' =>'Frontend\ProductController@getSubCategoryProduct']);
Route::resource('/item','Frontend\ProductController');

//search for products in frontend
Route::get('/searchitem',['as' =>'item.getsearch', 'uses' => 'Frontend\ProductController@getSearch']);

//for product enquiry form
Route::resource('enquire','EnquiryController');
// enquiry mail
// Route::get('/enquire/{slug}','Frontend\ProductController@getEnquire');
// Route::post('/enquire','Frontend\ProductController@postEnquire');

// frone end ends------------------------------------------------------------------------

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => ['auth']], function(){
	// products
	Route::post('product/fetch','ProductController@fetch');
	Route::post('product/fetchsub','ProductController@fetchsub');
	Route::post('product/fetchsubcat1','ProductController@fetchsubcat1');
	Route::delete('product/delete/{slug}', ['as' => 'product.destroysearch', 'uses' => 'ProductController@destroysearch']);
	Route::resource('product','ProductController');

	Route::get('/search','ProductController@getSearch');
	

	// Route::get('/getcategoryproduct/{category_id}','ProductController@getCategoryProduct');
	// Route::get('/getsubcategoryproduct/{subcategory_id}','ProductController@getSubCategoryProduct');
	// Route::get('/getsubcategory1product/{subcategory_id}','ProductController@getSubCategory1Product');

	// categories
	Route::get('category/{category_id}/subcategory','CategoryController@editSubCategory');
	Route::resource('category','CategoryController',['except' => ['create'],['destroy']]);

	// update subcategory
	Route::post('subcategory/', ['as' => 'subcategory.update', 'uses' => 'CategoryController@updatesubcategory']);
	// dashboard
	Route::get('/dashboard', 'PageController@getDashboard');
	// getting about page
	Route::get('/getabout', ['as' => 'page.getabout', 'uses' => 'PageController@getAbout']);
	Route::post('postabout', ['as' => 'page.about', 'uses' => 'PageController@postAbout']);
	// getting contact page
	// Route::get('/getcontact', 'PageController@getContact');
	// Route::post('postcontact', ['as' => 'page.contact', 'uses' => 'PageController@postcontact']);

	//user registration
	Route::group(['middleware' => ['user']],function(){
		Route::resource('users','UserController');
	});
	Route::get('/profile/{user_id}','UserController@getProfile');
	Route::post('/profile/edit',['as' => 'profile.edit', 'uses' => 'UserController@updateInformation']);
	Route::get('enquiries/{slug}',['as' => 'enquire.list','uses' => 'EnquiryController@showenquiries']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Contracts\Auth\MustVerifyEmail;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function checkPassword($oldpwd, $pwd)
    {
        if (Hash::check($oldpwd, $pwd))
        {
            return true;
        }
        else{
            return false;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Redirect;

use App\User;
use Session;
class UserController extends Controller
{
	public function __construct(){
        $this->middleware('user',['except' => ['getProfile','updateInformation']]);
        $this->middleware('auth');
    }

    public function getProfile($id){
        $userinfo = User::find($id);
        return view('user.profile')->with('userinfo',$userinfo);
    }

    public function create()
    {
        return view('user.create');
    }

    public function store(Request $request)
    {
        // validation
        $this->validate($request, array(
            'name' => 'required|min:2|max:50',
            'email' => 'required|email',
            'password' => 'required|min:5|max:20',
            'repassword' => 'required|min:5|max:20',
            'role' => 'required'));
        
        // store
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role = $request->role;	

        $user->save();  

        Session::flash('success','User was successfully created !');
        
        return redirect()->route('users.index');
    }

    public function index(){
    	$users = User::all();
    	return view('user.index')->with('users',$users);
    }


    public function edit($id)
    {
        $user = User::find($id);
        return view('user.edit')->with('user',$user);
    }

    public function destroy($id){
    	$user = User::find($id);
    	$user->delete();

    	Session::flash('success','User Removed Successfully');

    	return redirect()->route('users.index');
    }

    public function update(Request $request, $id){
    	$user = User::find($id);

    	$this->validate($request, array(
            'name' => 'required|min:2|max:50',
            'email' => 'required|email',
            'role' => 'required'));

    	$user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->role = $request->input('role');
        $user->save();

    	Session::flash('success','User Updated Successfully');

    	return redirect()->route('users.index');
    }

    public function updateInformation(Request $request){
        $id = $request->input('userId');
        $user = User::find($id);

        $oldpwd = $request->input('oldpassword');
        if($oldpwd != null)
        {
            if(User::checkPassword($oldpwd, $user->password))
            {
                // dd('old password matches');
                $this->validate($request, array(
                    'name' => 'required|min:2|max:50',
                    'email' => 'required|email',
                    'password' => [
                    'required',
                    'string',
                    'min:6',             // must be at least 6 characters in length
                    // 'regex:/[a-z]/',      // must contain at least one lowercase letter
                    // 'regex:/[A-Z]/',      // must contain at least one uppercase letter
                    // 'regex:/[0-9]/',      // must contain at least one digit
                    // 'regex:/[@$!%*#?&]/', // must contain a special character
                    ],
                    'confirm-password' => 'same:password'));


                $user->name = $request->input('name');
                $user->email = $request->input('email');

                if($user->password != null)
                {
                    $user->password = Hash::make($request->password);
                }

                $user->save();

                Session::flash('success','Profile Updated Successfully');

                return Redirect::back();
                
            } 
            else
            {
                // dd('old pw doesnt match');
            return Redirect::back()->withErrors('Old password doesnt match our records !!!');
            }
        }

        if($request->input('name') !=null && $request->input('email') !=null && $oldpwd == null && $request->input('password') !=null || $request->input('confirm-password') !=null){
            return Redirect::back()->withErrors('Please Enter Your Old Password First !!!');  
        }
        
        if($oldpwd == null)
        {    
            $this->validate($request, array(
                'name' => 'required|min:2|max:50',
                'email' => 'required|email'));

            $user->name = $request->input('name');
            $user->email = $request->input('email');

            $user->save();

            Session::flash('success','Email and Username Updated Successfully');
            return Redirect::back();
        }
        
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('title','| Add User')
@section('pageheader','User')
@section('pageminiheader','')
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('users.index')}}"><i class="fas fa-users-cog"></i> User</a></li>
    <li class="active">Add User</li>
  </ol>
@endsection
@section('content')
    {!! Form::open(array('route' => 'users.store','id'=>'submitform')) !!}
    {{csrf_field() }}
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Add User</h3>
        </div>

        <div class="box-body">
          <div class="form-group">
            {{ Form::label('name','Name') }}
            {{ Form::text('name',null,array('class' => 'form-control')) }}
          </div>   
          
          <div class="form-group">
            {{ Form::label('email','Email') }}
            {{ Form::email('email',null,array('class' => 'form-control')) }}
          </div>    
          
          <div class="form-group">
            {{ Form::label('password','Password') }}
            {{ Form::password('password',array('class' => 'form-control password')) }}
          </div>

          <div class="form-group">
            {{ Form::label('repassword','Re-password') }}
            {{ Form::password('repassword',array('class' => 'form-control repassword')) }}    
            <label id="invalidpassword" class="" style="color: red; display: none;">Password and re-password doesnt match</label>
          </div>

          <div class="form-group">
            {{ Form::label('role','Role') }}
            <select name="role" id="" class="form-control">
              <option value=""> ------Select One-------</option>
              <option value="user">User</option>
              <option value="admin">Admin</option>
            </select>
          </div>

          <div class="form-group" style="margin-top: 20px;">
            <button type="submit" class="btn btn-primary">Add User</button>
            <button type="reset" class="btn btn-danger">Reset</button>  
           </div>

        </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
@endsection

@section('javascripts')
<script>
  $('#submitform').submit(function(e){
    var pass = $('.password').val();
    var repass = $('.repassword').val();
    
    if(pass != repass){
        $('#invalidpassword').show();
        e.preventDefault();
    }
    
  });
</script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('title','| Edit User') 
@section('pageheader','User') 
@section('pageminiheader','Edit User')
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('users.index')}}"><i class="fas fa-users-cog"></i> User</a></li>
    <li class="active">Edit User</li>
  </ol>
@endsection 
@section('content')
  <!-- add product form -->
  {!! Form::model($user, ['route' => ['users.update',$user->id],'method' =>'PUT']) !!}
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit User</h3>
        </div>
        
        <div class="box-body">
          <div class="form-group">
            {{ Form::label('name','Name') }}
            {{ Form::text('name',null,array('class' => 'form-control')) }}
          </div>
          
          <div class="form-group">
            {{ Form::label('email','Email') }}
            {{ Form::email('email',null,array('class' => 'form-control')) }}
          </div>  
                    
          <div class="form-group">
            {{ Form::label('role','Role') }}
            <select name="role" id="" class="form-control">
              @if($user->role == 'user')
                <option value="user">{{$user->role}}</option>
                <option value="admin">Admin</option>
              @else
                <option value="admin">{{$user->role}}</option>
                <option value="user">User</option>
            
              @endif
            </select>
          </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Update User</button>
                <a href="{{ route('users.index')}}" class="btn btn-danger">Cancel</a>  
            </div>
          </div>
        </div>
      </div>
  {!! Form::close() !!}

  <!-- form ends -->
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title','| View Users') 
@section('pageheader','User') 
@section('pageminiheader','View All Users')
@section('navigate')
  <ol class="breadcrumb">
    <li><i class="fas fa-users-cog"></i> User</a></li>
    <li class="active">View All Users</li>
  </ol>
@endsection 
@section('content')
<div class="col-sm-12 col-md-12 col-lg-12">
    <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th class="th-sm">#
            </th>
            <th class="th-sm">Name
            </th>
            <th class="th-sm">Email
            </th>
            <th class="th-sm">Role
            </th>
            <th class="th-sm">Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @php
            $count = 1;
        @endphp
        @foreach($users as $user)
            @if($user->id != 1)
                <tr>
                    <td>@php echo $count++ @endphp</td>
                    <td><a href="{{ url('profile/'. $user->id) }}">{{ $user->name }}</a></td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->role }}</td>
                    <td>
                        <a href="{{ route('users.edit', $user->id)}}" class="btn pull-left" id="editbtn"><i class="fas fa-pen" title="edit"></i></a> 
                        <!-- delete button -->
                        {{ Form::open(['route' => ['users.destroy', $user->id], 'method' => 'DELETE', 'id' => 'deleteform', 'onsubmit' => 'deletecheck(event)'] ) }} 
                            <!-- {!!  Form::submit('Remove User',['class' =>'btn btn-danger btn-xs pull-left deletebtn','style' =>'margin-left : 5px', 'id' => 'deletebtn']) !!} -->
                            <button type="submit" id="deletebtn" class="deletebtn"><i class="fas fa-trash-alt" title="delete"></i></button>
                        {!! Form::close() !!}
                        <!-- delete button -->
                    </td>
                </tr>
            @endif
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <th>#</th>
            <th>Name
            </th>
            <th>Email
            </th>
            <th>Role
            </th>
            <th>Actions
            </th>
        </tr>
    </tfoot>
    </table>

    <style>
          .deletebtn{
            color: red;
            margin-top: 4px;
            background: none;
            border: none;
          }      
    </style>

</div>
@endsection
@section('javascripts')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });
    </script>

    <script>
        function deletecheck(e)
        {          
            if(confirm('Are you Sure you want to remove user ?'))
            {
                $(this).submit();
            }
            else
            {
                e.preventDefault();
            }
        }    
            // $('.deletebtn').click(function(e){
            //     if(confirm('Are you Sure you want to remove user ?')){
            //         $('#deleteform').submit();
            //     }
            //     else{
            //         e.preventDefault();
            //     }
            // e.preventDefault();
            // });
    </script>

<!--data table ends  -->
@endsection