routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// frontend
// -------------------------------------------- front end -------------------------------------------------
Route::get('item/category/{slug}', ['as' => 'item.getproducts', 'uses' => 'Frontend\ProductController@showproducts']);
// Route::get('/item/fetch','Frontend\ProductController@fetch'); //fetchforsorting
// Route::post('item/index1',['as' => 'item.index1', 'uses' => 'Frontend\ProductController@index']);
Route::get('/','Frontend\ProductController@index');
Route::get('/about','Frontend\PageController@getAbout');

Route::get('/contact-us','Frontend\PageController@getContact');
Route::post('/contact-us','Frontend\PageController@postContact');

// store all product listing 
Route::get('/store',['as' => 'item.sort', 'uses' => 'Frontend\ProductController@getstore']);

// Route::get('/getCategoryProduct/{id}',['as'=>'item.getCategoryProduct','uses' =>'Frontend\ProductController@getCategoryProduct']);
// Route::get('/getSubCategoryProduct/{id}',['as'=>'item.getSubCategoryProduct','uses' =>'Frontend\ProductController@getSubCategoryProduct']);
Route::resource('/item','Frontend\ProductController');

//search for products in frontend
Route::get('/searchitem',['as' =>'item.getsearch', 'uses' => 'Frontend\ProductController@getSearch']);

//for product enquiry form
Route::resource('enquire','EnquiryController');
// enquiry mail
// Route::get('/enquire/{slug}','Frontend\ProductController@getEnquire');
// Route::post('/enquire','Frontend\ProductController@postEnquire');

// frone end ends------------------------------------------------------------------------

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => ['auth']], function(){
	// products
	Route::post('product/fetch','ProductController@fetch');
	Route::post('product/fetchsub','ProductController@fetchsub');
	Route::post('product/fetchsubcat1','ProductController@fetchsubcat1');
	Route::delete('product/delete/{slug}', ['as' => 'product.destroysearch', 'uses' => 'ProductController@destroysearch']);
	Route::resource('product','ProductController');

	Route::get('/search','ProductController@getSearch');
	

	// Route::get('/getcategoryproduct/{category_id}','ProductController@getCategoryProduct');
	// Route::get('/getsubcategoryproduct/{subcategory_id}','ProductController@getSubCategoryProduct');
	// Route::get('/getsubcategory1product/{subcategory_id}','ProductController@getSubCategory1Product');

	// categories
	Route::get('category/{category_id}/subcategory','CategoryController@editSubCategory');
	Route::resource('category','CategoryController',['except' => ['create'],['destroy']]);

	// update subcategory
	Route::post('subcategory/', ['as' => 'subcategory.update', 'uses' => 'CategoryController@updatesubcategory']);
	// dashboard
	Route::get('/dashboard', 'PageController@getDashboard');
	// getting about page
	Route::get('/getabout', ['as' => 'page.getabout', 'uses' => 'PageController@getAbout']);
	Route::post('postabout', ['as' => 'page.about', 'uses' => 'PageController@postAbout']);
	// getting contact page
	// Route::get('/getcontact', 'PageController@getContact');
	// Route::post('postcontact', ['as' => 'page.contact', 'uses' => 'PageController@postcontact']);

	//user registration
	Route::group(['middleware' => ['user']],function(){
		Route::resource('users','UserController');
	});
	Route::get('/profile/{user_id}','UserController@getProfile');
	Route::post('/profile/edit',['as' => 'profile.edit', 'uses' => 'UserController@updateInformation']);
	Route::get('enquiries/{slug}',['as' => 'enquire.list','uses' => 'EnquiryController@showenquiries']);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $fillable = [
		'name', 'rate', 'quantity', 'description', 'image', 'slug'
	];
	
	public function category(){
		return $this->belongsToMany('App\Category');
	}
	public function enquiry(){
		return $this->hasMany('App\Enquiry');
	}
}

app/Http/Controllers/Frontend/ProductController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use App\Category;
use Mail;
use Session;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $products=Product::orderBy('created_at','desc')->paginate(9);
            $categoryname = "Featured";

            // getting id to get subcategories
            $categories = Category::all();

            // $categoryid = $categories->where('slug', request()->category)->first()->id;
            $categoryid = null;
            $subcategories = null;
            $subcategoriescount = null;
            $select = "";
            $categoryslug =  request()->category;

        $categories = Category::orderBy('name')->get();
        return view('Frontend.theme.index')->with('categories',$categories)->with('products',$products)->with('categoryname',$categoryname)->withsubcategories($subcategories)->with('select',$select)->with('categoryslug',$categoryslug)->with('subcategoriescount',$subcategoriescount);

        //comment starts here 
        // if(request()->category && request()->sortby)
        // {
        //     $products = Product::whereHas('category', function($query){
        //         $query->where('slug',request()->category);
        //     })->orderBy('rate',request('sortby'))->paginate(12)->appends('sortby',request('sortby'));
        //     // $products=Product::orderBy('rate',request('sortby'))->paginate(12)->appends('sortby',request('sortby'));
        //      $select = $request->get('sortby');

        //     if($select == 'default'){
        //         $products = Product::whereHas('category', function($query){
        //         $query->where('slug',request()->category);
        //         })->inRandomOrder()->paginate(12)->appends('sortby',request('sortby'));
        //     }
        //     $categories = Category::all();
        //     $categoryname = $categories->where('slug', request()->category)->first()->name;
            
        //     // getting id to get subcategories
        //     $categoryid = $categories->where('slug', request()->category)->first()->id;
        //     $subcategories = $categories->where('pid', '=', $categoryid );
        //     $subcategoriescount = count($subcategories);

        //     $categoryslug =  request()->category;
        // }
        // elseif(!request()->category && request()->sortby)
        // {
        //     // $products = Product::whereHas('category', function($query){
        //     //     $query->where('slug',request()->category);
        //     // })->orderBy('rate',request('sortby'))->paginate(12)->appends('sortby',request('sortby'));
        //     $products=Product::orderBy('rate',request('sortby'))->paginate(12)->appends('sortby',request('sortby'));
        //      $select = $request->get('sortby');

        //     if($select == 'default'){
        //         $products = Product::inRandomOrder()->paginate(12);
        //     }
        //     $categoryname = "Featured";
            
        //     // getting id to get subcategories
        //     $categories = Category::all();
        //     $categoryid = null;
        //     $subcategories = null;
        //     $subcategoriescount = null;

        //     // $categoryid = $categories->where('slug', request()->category)->first()->id;
        //     // $subcategories = $categories->where('pid', '=', $categoryid );
        //     // $subcategoriescount = count($subcategories);

        //     $categoryslug =  request()->category;
        // }

        // elseif(request()->category)
        // {
        //     $products = Product::whereHas('category', function($query){
        //         $query->where('slug',request()->category);
        //     })->paginate(3);
        //     $categories = Category::all();
        //     $categoryname = $categories->where('slug', request()->category)->first()->name;
        //     $categoryslug =  request()->category;
            
        //     // getting id to get subcategories
        //     $categoryid = $categories->where('slug', request()->category)->first()->id;
        //     $subcategories = $categories->where('pid', '=', $categoryid );
        //     $subcategoriescount = count($subcategories);
        //     $select = "";
        // }
        
        // else{
        //     $products=Product::inRandomOrder()->paginate(12);
        //     $categoryname = "Featured";

        //     // getting id to get subcategories
        //     $categories = Category::all();

        //     // $categoryid = $categories->where('slug', request()->category)->first()->id;
        //     $categoryid = null;
        //     $subcategories = null;
        //     $subcategoriescount = null;
        //     $select = "";
        //     $categoryslug =  request()->category;
        // }

        // $categories = Category::orderBy('name')->get();
        // return view('Frontend.index')->with('categories',$categories)->with('products',$products)->with('categoryname',$categoryname)->withsubcategories($subcategories)->with('select',$select)->with('categoryslug',$categoryslug)->with('subcategoriescount',$subcategoriescount);
    }

    public function getSearch(Request $request)
    {
        if(request()->search)
        {
            $query = request()->search;
            if(request()->sortby == 'default')
            {
                $products = Product::inRandomOrder()->where('name', 'LIKE', '%'.request()->search.'%')->paginate(9);
            }
            elseif(request()->sortby == 'atoz')
            {
                $products = Product::where('name', 'LIKE', '%'.request()->search. '%')->orderBy('name','asc')->paginate(9);
                $select = $request->get('sortby');
            }
            elseif(request()->sortby == 'ztoa')
            {
                $products = Product::where('name', 'LIKE', '%'.request()->search. '%')->orderBy('name','desc')->paginate(9);
                $select = $request->get('sortby');
            }
            else
            {
                $products = Product::where('name', 'LIKE', '%'.request()->search. '%')->orderBy('rate',request('sortby'))->paginate(9);
            }
            $productsforcount = Product::where('name', 'LIKE', '%'.request('search').'%')->get();
            $productcount = count($productsforcount)." results found";
            
            $categories = Category::orderBy('name')->get();
            
            $select = $request->get('sortby');
            return view('Frontend.theme.searchresults')->with('products',$products)->with('categories',$categories)->with('productcount',$productcount)->with('searchquery',$query)->with('select',$select);  
        }    
        else
        {
            $query = $request->get('searchtext');
            $products = Product::where('name', 'LIKE', '%'.$query.'%')->paginate(9);
            $productsforcount = Product::where('name', 'LIKE', '%'.$query.'%')->get();

            $productcount = count($productsforcount)." item found";

            $categories = Category::orderBy('name')->get();
            
            $select = $request->get('sortby');
            return view('Frontend.theme.searchresults')->with('products',$products)->with('categories',$categories)->with('productcount',$productcount)->with('searchquery',$query)->with('select',$select);
        }    
    }

    //getting enquiry message
    public function getEnquire($slug)
    {
        $products = Product::where('slug', '=', $slug )->get();
        return view('Frontend.enquire')->withProducts($products);
    }

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $product = Product::where('slug', '=', $slug)->first();

        $similarproduct1 = Product::inRandomOrder()->first();
        $similarproduct2 = Product::inRandomOrder()->first();
        $similarproduct3 = Product::inRandomOrder()->first();
        $similarproduct4 = Product::inRandomOrder()->first();

        // $similarproducts = Product::inRandomOrder()->limit(8)->get();

        $categories = Category::orderBy('name')->get();
        return view('Frontend.theme.about')->with('product',$product)->with('categories',$categories)->with('similarproduct1',$similarproduct1)->with('similarproduct2',$similarproduct2)->with('similarproduct3',$similarproduct3)->with('similarproduct4',$similarproduct4);
    }

// get products inside  category
    public function showproducts($slug)
    {
        $categoryname = Category::where('slug', '=', $slug)->first();
        $products = $categoryname->product()->paginate(12);
        
        $categories = Category::orderBy('name')->get();
        
        $categorylist = Category::where('slug', '=', $slug)->get();
        $subcategories = Category::all();


        return view('Frontend.theme.categoryitem')->with('categorylist',$categorylist)->with('categories',$categories)->withsubcategories($subcategories)->with('categoryname',$categoryname)->with('products',$products);
    } 
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function getstore(Request $request)
    {
        $productcount = Product::get();
        $count=$productcount->count();
        //comment starts here 

resources/views/products/create.blade.php
@extends('layouts.app')
@section('title','| Add Product')
@section('pageheader','Product')
@section('pageminiheader','Add Product')
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('product.index')}}"><i class="fas fa-box-open"></i> Product</a></li>
    <li class="active"><a href="{{route('product.create')}}">Add Product</li></a>
  </ol>
@endsection
@section('content')
{!! Form::open(array('route' => 'product.store','files' => 'true')) !!}
  <div class="col-md-7">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Add Product</h3>
      </div>
      
      <div class="box-body">
        <div class="form-group">
          {{ Form::label('name','Name') }}
          {{ Form::text('name',null,array('class' => 'form-control')) }}
        </div>

        <div class="form-group">
          {{Form::label('image','Image') }}
          {{ Form::file('image', ['class'=>'form-control']) }}
        </div>

        <div class="form-group">
          <div class="col-md-6">
            {{ Form::label('quantity','Quantity') }}
            {{ Form::number('quantity',null,array('class' => 'form-control')) }}
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-md-6">
            {{ Form::label('rate','Rate') }}
            {{ Form::number('rate',null,array('class' => 'form-control')) }}
          </div>
        </div>
      </div>
    </div>

    <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Description</h3>
        </div>
      
        <div class="box-body">
          <div class="form-group">
            {{ Form::textarea('description', $value = null, ['class' => 'form-control', 'rows' => 3]) }}
          </div>
        </div>
      </div>
  </div>
  
  <div class="col-md-5">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Select Category</h3>
      </div>

      <div class="box-body">  
        <div class="form-group">
          @foreach($categories as $cats)
          @if($cats->pid == 0 )
            <div class="checkbox">
              <label>
                <input type="checkbox" value="{{$cats->id}}" name="category_id[]">  {{ $cats->name}}
              </label>

              <ul style="text-decoration: none; list-style: none;">
                @foreach($categories as $subcat)
                @if($subcat->pid == $cats->id)
                  <li>
                    <label>
                      <input type="checkbox"  value="{{$subcat->id}}" name="category_id[]"> {{ $subcat->name}}
                    </label>
                  </li>
                  
                  @foreach($categories as $subcat1)
                  @if($subcat1->pid == $subcat->id)
                  <ul style="text-decoration: none; list-style: none;">
                    <li>
                      <label for="">
                        <input type="checkbox"  value="{{$subcat1->id}}" name="category_id[]"> {{ $subcat1->name}}
                      </label>
                      @foreach($categories as $subcat2)
                      @if($subcat2->pid == $subcat1->id)
                      <ul style="text-decoration: none; list-style: none;">
                        <li>
                          <label for="">
                            <input type="checkbox"  value="{{$subcat2->id}}" name="category_id[]"> {{ $subcat2->name}}
                          </label>
                        </li>
                      </ul>
                      @endif
                      @endforeach
                    </li>
                  </ul>
                  @endif
                  @endforeach

                @endif
                @endforeach
              </ul>
              <hr>
            </div>
          @endif
          @endforeach
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add Product</button>
            <button type="reset" class="btn btn-danger">Reset</button>  
        </div>
      </div>
    </div>
  </div>
  <!-- <div class="col-md-6">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Category</h3>
      </div>

      <div class="box-body">        
        <div class="form-group">
          {{ Form::label('category_id','Category') }}
          <select name="category_id" id="" class="form-control">
            <option value=""> ------Select One-------</option>
            @foreach($categories as $category)
            <option value="{{ $category->id}}"> {{ $category->name }} </option>
            @endforeach
          </select>  
        </div>
        
        <div class="form-group">
          {{ Form::label('subcategory_id','Category') }}
          <select name="sub_category" id="sub_category" class="form-control">
            <option value=""></option>
          </select>
        </div>
        
        <div class="form-group">
          {{ Form::label('subcategory1_id','Category') }}
          <select name="sub_category1" id="sub_category1" class="form-control">
            <option value=""></option>
          </select>
        </div>
      </div>

    </div>
  </div> -->

{!! Form::close() !!}


         

          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
          <script>
              $.ajaxSetup({
                 headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                  }
                });
                $('select[name="category_id"]').on('change',function(){
                    var category_id = $(this).val();
                    if(category_id){
                    $.ajax({
                        url: '/product/fetch',
                        type: 'POST',
                        dataType : 'json',
                        data: {id:category_id, _token: '{{csrf_token()}}' },
                        success: function(data){
                        $('#sub_category').html();
                        $("#sub_category").html(data);
                      }
                    })
                  }
                  $('#sub_category').empty();
                  $('#sub_category1').empty();                  
                })
                $('select[name="sub_category"]').on('change',function(){
                    var subcategory_id = $(this).val();
                    
                    if(subcategory_id){
                    $.ajax({
                        url: '/product/fetchsub',
                        type: 'POST',
                        dataType : 'json',
                        data: {id:subcategory_id, _token: '{{csrf_token()}}' },
                        success: function(data){
                        $('#sub_category1').html();
                        $("#sub_category1").html(data);
                      }
                    })
                  }
                })
          </script>

    <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('vendor/unisharp/laravel-ckeditor/adapters/jquery.js') }}"></script>
    <script>
        $('textarea').ckeditor();
    </script>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title','| View Products') 
@section('pageheader','Product') 
@section('pageminiheader','View All Products') 
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('product.index')}}"><i class="fas fa-box-open"></i> Product</a></li>
    <li class="active">View All</li>
  </ol>
@endsection
@section('content')
<div class="col-md-12">
    <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="th-sm">#
                </th>
                <th class="th-sm">Name
                </th>
                <th class="th-sm">Rate
                </th>
                <th class="th-sm">Quantity
                </th>
                <th class="th-sm">Category
                </th>
                <th class="th-sm">Description
                </th>
                <th class="th-sm">Image
                </th>
                <th class="th-sm">Purchase Date
                </th>
                <th class="th-sm">Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @php
                $count = 1;
            @endphp
            @foreach($products as $product)
            <tr>
                <td>@php echo $count++ @endphp</td>
                <td>{{ $product['name']}}</td>
                <td>{{ $product['rate']}}</td>
                <td>{{ $product['quantity']}}</td>
                <td>
                    @foreach($product->category as $cats)
                        <a href="{{ route('category.show', $cats->id) }}">
                            <span class="badge badge-primary" style="background-color: #6196ed">{{ $cats->name }}</span>
                        </a>
                        <br>
                    @endforeach
                </td>
                <td>{!! substr($product['description'],0,20) !!}{{ (strlen($product['description']))>10 ? '....' : '' }}</td>
                <td style="text-align: center;">
                    <a href="{{ asset('images/' .$product['image'] ) }}">
                        <img src="{{ asset('images/' . $product['image'] .'-thumbs.png') }}" alt="" class="">    
                    </a>            
                </td>
                <td>{{ date('M j, Y h:ia',strtotime( $product['created_at'])) }}</td>
                <td>
                    <!-- delete button -->
                    {{ Form::open(['route' => ['product.destroy', $product['id']], 'method' => 'DELETE', 'id' => 'deleteform', 'class' =>'pull-right','onclick' => 'deleteproduct(event)']) }} 
                        <!-- {!!  Form::submit('Delete',['class' =>'btn btn-xs delelteprod','style' =>'margin-top : 0px', 'id' => 'deletebtn']) !!}  -->
                        <button type="submit" id="deletebtn" class="deleteprod"><i class="fas fa-trash-alt pull-left" title="delete"></i></button>
                    {!! Form::close() !!}
                    <!-- delete button -->
                    <a href="{{ route('product.edit', $product['id'])}}"> <i class="fas fa-pen pull-right" title="edit"></i></a>
                    <a href="{{ route('product.show', $product['slug'])}}"><i class="fas fa-eye pull-left" title="view" ></i></a>
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>#</th>
                <th>Name
                </th>
                <th>Rate
                </th>
                <th>Quantity
                </th>
                <th>Category
                </th>
                <th>Description
                </th>
                <th>Image
                </th>
                <th>Purchase Date
                </th>
                <th>Actions
                </th>
            </tr>
        </tfoot>
    </table>

    <style>
          .deleteprod{
            color: red;
            background: none;
            border: none;
          }      
    </style>

</div>
@endsection
@section('javascripts')
    
    
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');     
        });
    </script>

    <script>
    function deleteproduct(e){
            if(confirm('Are you Sure you want to delete ?')){
                $(this).submit();
            }
            else{
                e.preventDefault();
            }
        }
    </script>

<!--data table ends  -->
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('title','| View Products') 
@section('pageheader','Product') 
@section('pageminiheader','View Product') 
@section('navigate')
  <ol class="breadcrumb">
    <li><a href="{{route('product.index')}}"><i class="fas fa-box-open"></i> Product</a></li>
    <li class="active">View Product</li>
  </ol>
@endsection
@section('content')
    <div class="row" style="background-color: white;">
        @foreach($products as $product)
        <div class="col-md-4">
            <a href="{{ asset('images/' .$product['image'] ) }}">            
                <img src="{{ asset('images/' . $product->image ) }}" alt="" class="img-fluid product-image">            
            </a>
        </div>

        <div class="col-md-7 product-description">
            <h2 class="">{{ $product->name}}</h2>
            
            <p> <b id="rate">Rs : {{ $product->rate}} </b></p>
            <p> <b>Quantity :  </b>{{ $product->quantity}}</p>
            <p> 
                <b>Categories :  </b>
                @foreach($product->category as $cats)
                    <a href="{{ route('category.show', $cats->id) }}">
                        <span class="badge badge-primary" style="background-color: #6196ed; height: 20px;"> {{ $cats->name }} </span>
                    </a>
                @endforeach
            </p>
            <p> <b>Purchased Date  : </b>{{ date('M j, Y h:ia',strtotime( $product->created_at)) }} </p>
            <p style=""> <b>Description :  </b>{!! $product->description !!} </p>
            <p>
                <a href="{{route('product.edit', $product->id)}}" class="btn btn-default btn-sm"> Edit </a>
                {{ Form::open(['route' => ['product.destroy', $product->id], 'method' => 'DELETE', 'id' => 'deleteform']) }} 
                    {!! Form::submit('Delete',['class' =>'btn btn-danger btn-sm', 'id'=>'deletebtn']) !!} 
                {!! Form::close() !!}
            </p>
        </div>
        @endforeach
    </div>
    
    <style>
        .product-image
        {
            margin: 5px;
            height: 350px;
            width: auto;
            object-fit: contain;
        }
        .product-description>p{
            font-size: 17px;
        }
        .product-description>p #rate{
            font-size: 40px;
            color : orange;
        }
        .product-description>p>b{
            font-size: 17px;
        }
        .product-description>p>a{
            margin-top: 20px;
            font-size: 16px;
        }
        #deletebtn{
            margin-top: -46px;
            margin-left: 60px;
            color: white;
            font-size: 16px;
        }
    </style>

@endsection

@section('javascripts')
    <script>
    $(document).ready(function(){
        $('#deletebtn').click(function(e){
            if(confirm('Are You Sure ??')){
                $('#deleteform').submit();
            }
            else{
                e.preventDefault();
            }
        e.preventDefault();
        });
    });
    </script>
@endsection